### ISSUE TITLE
Commenting line in PR does not work

### ISSUE THREAD

**Issue by fho** [AGhost-7/critiq.vim#29]
I tried to comment a line in a PR via critiq but the comment did not show up.

I opened the PR and used `:CritiqCommentLine` on a diff line that changed in the PR.
I wrote something and closed the scratch window with `:q`.
The comment did not show up in the PR. I did not got any error message.

I'm using nvim v0.3.4 + critiq 3852670

**Comment by AGhost-7** [comment]
You have to call `:CritiqSubmitComment`. I've clarified this in the documentation, thanks for the feedback.
