### ISSUE TITLE
Integrate with fugitive for diffs

### ISSUE THREAD

**Issue by picaoao** [AGhost-7/critiq.vim#30]
Great plugin, is there anyway of viewing the diffs with/like `vim-fugitive` ?

**Comment by AGhost-7** [comment]
Not at the moment, I'd need to automatically add git remotes for this to work. It currently pulls a patch from the github api instead.

**Comment by picaoao** [comment]
how hard would that be ? it would be a beautiful if we could have it !

**Comment by AGhost-7** [comment]
Since this view needs to be loaded asynchronously (couple of network calls happen at the same time for things to load quickly), probably a fair bit of work involved. I'd also need to find a namespacing scheme for the remotes which are automatically added.

**Comment by AGhost-7** [comment]
Won't be implementing since the plugin is designed to do asynchronous calls.
