### ISSUE TITLE
Support `diffsplit` in PR  

### ISSUE THREAD

**Issue by dzhang-b** [AGhost-7/critiq.vim#32]
Hi,

First, Thanks for this awesome project.

Is it possible to open github diff in the vimdiff mode? it is `diffsplit somefile` ?

I used `git difftools` and `vimdiff` a lot. I think the diff mode display is much better than reading github diff file.

Beside direct support for PR diff view, is it possible to pull the PR branch locally and then view it inside `!git difftools` for example? I know it might be or might not be harder to set `CritiqCommentLine` in `diffsplit` mode.

Thanks again for the awesome plugin.

**Comment by AGhost-7** [comment]
To my knowledge, vimdiff only supports diffing one file at a time. Most PRs I review are multiple files.

**Comment by dzhang-b** [comment]
@AGhost-7 yeah, but it can be a queue of files to be reviewed. git difftools does that and it automatically opens the next file to be reviewed if you close the current diffs.

**Comment by AGhost-7** [comment]
Personally this isn't how I'd want to review a PR. I scan the whole changes first then look in higher detail each file. I don't think vim diff is going to work.

If you're interested in implementing this I would accept a PR as an opt-in feature (meaning the old behaviour would be the default).

**Comment by dzhang-b** [comment]
@AGhost-7 I found that in diff page I can type `gf` on the diff content and go to that file. It is very useful and I dont think this feature is needed for now. Thanks!
