### ISSUE TITLE
Viewing a comment thread

### ISSUE THREAD

**Issue by kthibodeaux** [AGhost-7/critiq.vim#5]
Firstly, I just discovered this plugin today after looking for something like it for a long time.  Thank you for providing this!

I looked around the source but could not find this.

Is there a feature planned to view a comment chain on a line?  Maybe a binding that opens a read-only split that shows the comment chain?

**Comment by AGhost-7** [comment]
I definitively ran into the need to view a comment chain a few times and had to resolve to opening the PR in Github. This is something that I have the intention of implementing.

**Comment by AGhost-7** [comment]
`:CritiqListComments` added and merged into master.
